"""add persisted incident detections

Revision ID: 67e62e933b92
Revises: 0ae2d3afe139
Create Date: 2026-08-21 06:40:33.722573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67e62e933b92'
down_revision: Union[str, Sequence[str], None] = '0ae2d3afe139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('detector', sa.String(length=120), nullable=False),
    sa.Column('signal', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_detector'), 'detections', ['detector'], unique=False)
    op.create_index(op.f('ix_detections_incident_id'), 'detections', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_incident_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_detector'), table_name='detections')
    op.drop_table('detections')
    # ### end Alembic commands ###
