"""add github remediation metadata

Revision ID: a32f409de83e
Revises: fa7d4d8c9117
Create Date: 2026-08-21 14:38:39.287962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32f409de83e'
down_revision: Union[str, Sequence[str], None] = 'fa7d4d8c9117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_candidates', sa.Column('github_pr_number', sa.Integer(), nullable=True))
    op.add_column('repair_candidates', sa.Column('github_pr_branch', sa.String(length=255), nullable=True))
    op.add_column('repair_candidates', sa.Column('github_commit_sha', sa.String(length=100), nullable=True))
    op.add_column('repair_candidates', sa.Column('github_pr_url', sa.String(length=1000), nullable=True))
    op.add_column('repair_candidates', sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_repair_candidates_github_pr_number'), 'repair_candidates', ['github_pr_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repair_candidates_github_pr_number'), table_name='repair_candidates')
    op.drop_column('repair_candidates', 'merged_at')
    op.drop_column('repair_candidates', 'github_pr_url')
    op.drop_column('repair_candidates', 'github_commit_sha')
    op.drop_column('repair_candidates', 'github_pr_branch')
    op.drop_column('repair_candidates', 'github_pr_number')
    # ### end Alembic commands ###
